# Generated by Django 2.0.4 on 2018-04-24 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('version', models.CharField(max_length=20)),
                ('android', models.CharField(max_length=20)),
                ('ios', models.CharField(max_length=20)),
                ('timestamp', models.IntegerField()),
                ('jsPath', models.URLField()),
            ],
        ),
    ]
