# Generated by Django 2.0.4 on 2018-04-25 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Package', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='package',
            name='changelog',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='package',
            name='isForceUpdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='package',
            name='jsPath',
            field=models.URLField(null=True),
        ),
    ]
